from pathlib import Path
from typing import Protocol


class FileStorage(Protocol):
    def read_text(self, path: Path) -> str: ...

    def write_text(self, path: Path, content: str) -> None: ...

    def exists(self, path: Path) -> bool: ...

    def ensure_dir(self, path: Path) -> None: ...


class JsonStore(Protocol):
    def load(self) -> dict: ...

    def save(self, data: dict) -> None: ...
