from typing import Protocol
from .models import LessonSession, ChatMessage, EndJobStatus


class LessonSessionRepository(Protocol):
    def get_active(self) -> LessonSession | None: ...

    def save(self, session: LessonSession) -> None: ...

    def clear(self) -> None: ...


class LessonManager(Protocol):
    def get_session(self) -> LessonSession | None: ...

    def start_new(self, teacher_name: str, teacher_display: str) -> LessonSession: ...

    def add_message(self, role: str, content: str) -> None: ...

    def start_end_job(self, job_id: str) -> None: ...

    def update_end_job(self, status: str, updated_files: list[str] | None = None, error: str | None = None) -> None: ...

    def get_end_job(self) -> EndJobStatus | None: ...

    def has_ended(self) -> bool: ...
