from typing import Protocol


class TeacherProfileRepository(Protocol):
    def get_teacher_names(self) -> list[str]: ...

    def get_teacher_display(self, name: str) -> str: ...

    def get_persona(self, name: str) -> str: ...

    def get_diary_recent(self, max_chars: int = 5000) -> str: ...

    def get_wechat_context(self) -> str: ...

    def determine_next_teacher(self, progress_text: str) -> str: ...
