from typing import Protocol

from .models import CreateTextbookCommand, TextbookRecord


class TextbookCatalog(Protocol):
    def list_textbooks(self, show_deleted: bool = False) -> list[TextbookRecord]: ...

    def get_by_id(self, textbook_id: str) -> TextbookRecord | None: ...

    def get_active(self) -> TextbookRecord | None: ...

    def create(self, command: CreateTextbookCommand) -> TextbookRecord: ...

    def activate(self, textbook_id: str) -> TextbookRecord: ...

    def mark_completed(self, textbook_id: str) -> TextbookRecord: ...

    def soft_delete(self, textbook_id: str) -> TextbookRecord: ...

    def restore(self, textbook_id: str) -> TextbookRecord: ...

    def get_active_id(self) -> str | None: ...

    def get_active_paths(self) -> tuple[str | None, str | None]: ...

    def has_active_textbook(self) -> bool: ...

    def update_content_path(self, textbook_id: str, content_path: str) -> None: ...

    def update_progress_path(self, textbook_id: str, progress_path: str) -> None: ...

    def update_source_ref(self, textbook_id: str, source_ref: str) -> None: ...

    def update_original_path(self, textbook_id: str, original_path: str) -> None: ...

    def set_import_error(self, textbook_id: str, error: str) -> None: ...

    def set_import_ready(self, textbook_id: str) -> None: ...

    def set_import_processing(self, textbook_id: str) -> None: ...

    def mark_pending_activation(self, textbook_id: str) -> None: ...
