from typing import Protocol
from .models import TextbookRecord, CreateTextbookCommand


class TextbookCatalog(Protocol):
    def list_textbooks(self, show_deleted: bool = False) -> list[TextbookRecord]: ...

    def get_by_id(self, textbook_id: str) -> TextbookRecord | None: ...

    def get_active(self) -> TextbookRecord | None: ...

    def create(self, command: CreateTextbookCommand) -> TextbookRecord: ...

    def activate(self, textbook_id: str) -> TextbookRecord: ...

    def mark_completed(self, textbook_id: str) -> TextbookRecord: ...

    def soft_delete(self, textbook_id: str) -> TextbookRecord: ...

    def restore(self, textbook_id: str) -> TextbookRecord: ...
